name: Publish

on:
  push:
    tags: [ "v*.*.*" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@4b3306307f536bbfcb559603629b3b4f6aef5ab8
        with:
          python_version: '3.11'
          pypi_token: ${{ secrets.PYPI_TOKEN }}
